#index:
#    path: /
#    controller: App\Controller\DefaultController::index

welcome_page:
  path: /welcome
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: welcome.html.twig